<Project>

  <PropertyGroup>
    <Version>0.1.1</Version>
    <Authors>Derek</Authors>
    <Company>Derek</Company>
    <Description>Reconstructs SQL Server INSERT/UPDATE/DELETE history from fn_dblog without requiring Audit, CDC, or Change Tracking to have been enabled beforehand.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/caidarek/LogCarver</RepositoryUrl>
    <PackageProjectUrl>https://github.com/caidarek/LogCarver</PackageProjectUrl>
  </PropertyGroup>

</Project>
